export const KATEX_COMMAND_PREVIEWS: Record<string, string> = {
  '*': '*',
  '/': '/',
  '<': '<',
  '>': '>',
  ':': ':',
  '~': '~',
  '\\Alpha': 'A',
  '\\Beta': 'B',
  '\\Epsilon': 'E',
  '\\Zeta': 'Z',
  '\\Eta': 'H',
  '\\Iota': 'I',
  '\\Kappa': 'K',
  '\\Mu': 'M',
  '\\Nu': 'N',
  '\\Omicron': 'O',
  '\\Rho': 'P',
  '\\Tau': 'T',
  '\\Chi': 'X',
  '\\omicron': 'o',
  '\\thetasym': 'ϑ',
  '\\varGamma': 'Γ',
  '\\varDelta': 'Δ',
  '\\varTheta': 'Θ',
  '\\varLambda': 'Λ',
  '\\varXi': 'Ξ',
  '\\varPi': 'Π',
  '\\varSigma': 'Σ',
  '\\varUpsilon': 'Υ',
  '\\varPhi': 'Φ',
  '\\varPsi': 'Ψ',
  '\\varOmega': 'Ω',
  '\\lparen': '(',
  '\\rparen': ')',
  '\\lbrack': '[',
  '\\rbrack': ']',
  '\\lbrace': '{',
  '\\rbrace': '}',
  '\\langle': '⟨',
  '\\rangle': '⟩',
  '\\lang': '⟨',
  '\\rang': '⟩',
  '\\lt': '<',
  '\\gt': '>',
  '\\vert': '|',
  '\\Vert': '‖',
  '\\lvert': '|',
  '\\rvert': '|',
  '\\lVert': '‖',
  '\\rVert': '‖',
  '\\lceil': '⌈',
  '\\rceil': '⌉',
  '\\lfloor': '⌊',
  '\\rfloor': '⌋',
  '\\lmoustache': '⎰',
  '\\rmoustache': '⎱',
  '\\lgroup': '⟮',
  '\\rgroup': '⟯',
  '\\ulcorner': '⌜',
  '\\urcorner': '⌝',
  '\\llcorner': '⌞',
  '\\lrcorner': '⌟',
  '\\llbracket': '⟦',
  '\\rrbracket': '⟧',
  '\\lBrace': '⦃',
  '\\rBrace': '⦄',
  '\\backslash': '\\',
  '\\uparrow': '↑',
  '\\downarrow': '↓',
  '\\updownarrow': '↕',
  '\\Uparrow': '⇑',
  '\\Downarrow': '⇓',
  '\\Updownarrow': '⇕',
  '\\left': '(x',
  '\\middle': 'x|y',
  '\\right': 'x)',
  '\\big': 'big (',
  '\\Big': 'Big (',
  '\\bigg': 'bigg (',
  '\\Bigg': 'Bigg (',
  '\\bigl': 'big (',
  '\\Bigl': 'Big (',
  '\\biggl': 'bigg (',
  '\\Biggl': 'Bigg (',
  '\\bigm': 'big |',
  '\\Bigm': 'Big |',
  '\\biggm': 'bigg |',
  '\\Biggm': 'Bigg |',
  '\\bigr': 'big )',
  '\\Bigr': 'Big )',
  '\\biggr': 'bigg )',
  '\\Biggr': 'Bigg )',
  '\\sum': '∑',
  '\\prod': '∏',
  '\\coprod': '∐',
  '\\int': '∫',
  '\\intop': '∫',
  '\\smallint': '∫',
  '\\iint': '∬',
  '\\iiint': '∭',
  '\\oint': '∮',
  '\\oiint': '∯',
  '\\oiiint': '∰',
  '\\bigotimes': '⨂',
  '\\bigoplus': '⨁',
  '\\bigodot': '⨀',
  '\\biguplus': '⨄',
  '\\bigsqcup': '⨆',
  '\\bigvee': '⋁',
  '\\bigwedge': '⋀',
  '\\bigcap': '⋂',
  '\\bigcup': '⋃',
  '\\pm': '±',
  '\\plusmn': '±',
  '\\mp': '∓',
  '\\cdotp': '·',
  '\\centerdot': '·',
  '\\circ': '∘',
  '\\circledast': '⊛',
  '\\circledcirc': '⊚',
  '\\circleddash': '⊝',
  '\\Cup': '⋓',
  '\\Cap': '⋒',
  '\\doublecap': '⋒',
  '\\doublecup': '⋓',
  '\\curlyvee': '⋎',
  '\\curlywedge': '⋏',
  '\\divideontimes': '⋇',
  '\\dotplus': '∔',
  '\\doublebarwedge': '⩞',
  '\\gtrdot': '⋗',
  '\\intercal': '⊺',
  '\\leftthreetimes': '⋋',
  '\\rightthreetimes': '⋌',
  '\\ldotp': '.',
  '\\rtimes': '⋊',
  '\\ltimes': '⋉',
  '\\setminus': '∖',
  '\\smallsetminus': '∖',
  '\\lessdot': '⋖',
  '\\lhd': '⊲',
  '\\rhd': '⊳',
  '\\unlhd': '⊴',
  '\\unrhd': '⊵',
  '\\amalg': '⨿',
  '\\And': '&',
  '\\ast': '*',
  '\\barwedge': '⊼',
  '\\bigcirc': '○',
  '\\boxdot': '⊡',
  '\\boxminus': '⊟',
  '\\boxplus': '⊞',
  '\\boxtimes': '⊠',
  '\\bullet': '•',
  '\\bmod': 'mod',
  '\\mod': 'mod',
  '\\pmod': '(mod)',
  '\\pod': '( )',
  '\\land': '∧',
  '\\lor': '∨',
  '\\odot': '⊙',
  '\\ominus': '⊖',
  '\\oplus': '⊕',
  '\\oslash': '⊘',
  '\\otimes': '⊗',
  '\\sqcap': '⊓',
  '\\sqcup': '⊔',
  '\\uplus': '⊎',
  '\\veebar': '⊻',
  '\\wr': '≀',
  '\\leq': '≤',
  '\\geq': '≥',
  '\\neq': '≠',
  '\\doteqdot': '≑',
  '\\eqcirc': '≖',
  '\\eqcolon': '≕',
  '\\minuscolon': '∹',
  '\\Eqcolon': '≕',
  '\\minuscoloncolon': '∺',
  '\\eqqcolon': '≕',
  '\\equalscolon': '≕',
  '\\Eqqcolon': '⩴',
  '\\equalscoloncolon': '⩴',
  '\\approxcolon': '≈:',
  '\\approxcoloncolon': '≈::',
  '\\approxeq': '≊',
  '\\asymp': '≍',
  '\\backepsilon': '∍',
  '\\backsim': '∽',
  '\\backsimeq': '⋍',
  '\\between': '≬',
  '\\bowtie': '⋈',
  '\\bumpeq': '≏',
  '\\Bumpeq': '≎',
  '\\circeq': '≗',
  '\\colonapprox': ':≈',
  '\\Colonapprox': '::≈',
  '\\coloncolonapprox': '::≈',
  '\\coloneq': ':=',
  '\\colonminus': ':-',
  '\\Coloneq': '::=',
  '\\coloncolonminus': '::-',
  '\\coloneqq': ':=',
  '\\colonequals': ':=',
  '\\Coloneqq': '::=',
  '\\coloncolonequals': '::=',
  '\\colonsim': ':∼',
  '\\Colonsim': '::∼',
  '\\coloncolonsim': '::∼',
  '\\cong': '≅',
  '\\curlyeqprec': '⋞',
  '\\curlyeqsucc': '⋟',
  '\\dashv': '⊣',
  '\\dblcolon': '∷',
  '\\coloncolon': '∷',
  '\\doteq': '≐',
  '\\Doteq': '≑',
  '\\eqsim': '≂',
  '\\eqslantgtr': '⪖',
  '\\eqslantless': '⪕',
  '\\equiv': '≡',
  '\\fallingdotseq': '≒',
  '\\frown': '⌢',
  '\\geqq': '≧',
  '\\geqslant': '⩾',
  '\\gg': '≫',
  '\\ggg': '⋙',
  '\\gggtr': '⋙',
  '\\gtrapprox': '⪆',
  '\\gtreqless': '⋛',
  '\\gtreqqless': '⪌',
  '\\gtrless': '≷',
  '\\gtrsim': '≳',
  '\\imageof': '⊷',
  '\\Join': '⋈',
  '\\leqq': '≦',
  '\\leqslant': '⩽',
  '\\lessapprox': '⪅',
  '\\lesseqgtr': '⋚',
  '\\lesseqqgtr': '⪋',
  '\\lessgtr': '≶',
  '\\lesssim': '≲',
  '\\ll': '≪',
  '\\lll': '⋘',
  '\\llless': '⋘',
  '\\models': '⊨',
  '\\multimap': '⊸',
  '\\origof': '⊶',
  '\\owns': '∋',
  '\\parallel': '∥',
  '\\perp': '⊥',
  '\\pitchfork': '⋔',
  '\\prec': '≺',
  '\\precapprox': '⪷',
  '\\preccurlyeq': '≼',
  '\\preceq': '⪯',
  '\\precsim': '≾',
  '\\risingdotseq': '≓',
  '\\shortmid': '∣',
  '\\shortparallel': '∥',
  '\\sim': '∼',
  '\\simeq': '≃',
  '\\smallfrown': '⌢',
  '\\smallsmile': '⌣',
  '\\smile': '⌣',
  '\\sqsubset': '⊏',
  '\\sqsubseteq': '⊑',
  '\\sqsupset': '⊐',
  '\\sqsupseteq': '⊒',
  '\\sub': '⊂',
  '\\sube': '⊆',
  '\\Subset': '⋐',
  '\\subseteqq': '⫅',
  '\\succ': '≻',
  '\\succapprox': '⪸',
  '\\succcurlyeq': '≽',
  '\\succeq': '⪰',
  '\\succsim': '≿',
  '\\supe': '⊇',
  '\\Supset': '⋑',
  '\\supseteqq': '⫆',
  '\\thickapprox': '≈',
  '\\thicksim': '∼',
  '\\trianglelefteq': '⊴',
  '\\triangleq': '≜',
  '\\trianglerighteq': '⊵',
  '\\varpropto': '∝',
  '\\vartriangle': '△',
  '\\vartriangleleft': '⊲',
  '\\vartriangleright': '⊳',
  '\\vcentcolon': ':',
  '\\ratio': ':',
  '\\vdash': '⊢',
  '\\vDash': '⊨',
  '\\Vdash': '⊩',
  '\\Vvdash': '⊪',
  '\\not': '≠',
  '\\gnapprox': '⪊',
  '\\gneq': '≩',
  '\\gneqq': '≩',
  '\\gnsim': '⋧',
  '\\gvertneqq': '≩',
  '\\lnapprox': '⪉',
  '\\lneq': '≨',
  '\\lneqq': '≨',
  '\\lnsim': '⋦',
  '\\lvertneqq': '≨',
  '\\ncong': '≇',
  '\\ngeq': '≱',
  '\\ngeqq': '≱',
  '\\ngeqslant': '≱',
  '\\ngtr': '≯',
  '\\nleq': '≰',
  '\\nleqq': '≰',
  '\\nleqslant': '≰',
  '\\nless': '≮',
  '\\nmid': '∤',
  '\\notni': '∌',
  '\\nparallel': '∦',
  '\\nprec': '⊀',
  '\\npreceq': '⋠',
  '\\nshortmid': '∤',
  '\\nshortparallel': '∦',
  '\\nsim': '≁',
  '\\nsubseteq': '⊈',
  '\\nsubseteqq': '⊈',
  '\\nsucc': '⊁',
  '\\nsucceq': '⋡',
  '\\nsupseteq': '⊉',
  '\\nsupseteqq': '⊉',
  '\\ntriangleleft': '⋪',
  '\\ntrianglelefteq': '⋬',
  '\\ntriangleright': '⋫',
  '\\ntrianglerighteq': '⋭',
  '\\nvdash': '⊬',
  '\\nvDash': '⊭',
  '\\nVDash': '⊯',
  '\\nVdash': '⊮',
  '\\precnapprox': '⪹',
  '\\precneqq': '⪵',
  '\\precnsim': '⋨',
  '\\subsetneq': '⊊',
  '\\subsetneqq': '⫋',
  '\\succnapprox': '⪺',
  '\\succneqq': '⪶',
  '\\succnsim': '⋩',
  '\\supsetneq': '⊋',
  '\\supsetneqq': '⫌',
  '\\varsubsetneq': '⊊',
  '\\varsubsetneqq': '⫋',
  '\\varsupsetneq': '⊋',
  '\\varsupsetneqq': '⫌',
  '\\circlearrowleft': '↺',
  '\\circlearrowright': '↻',
  '\\curvearrowleft': '↶',
  '\\curvearrowright': '↷',
  '\\Darr': '⇓',
  '\\dArr': '⇓',
  '\\darr': '↓',
  '\\dashleftarrow': '⇠',
  '\\dashrightarrow': '⇢',
  '\\downdownarrows': '⇊',
  '\\downharpoonleft': '⇃',
  '\\downharpoonright': '⇂',
  '\\gets': '←',
  '\\Harr': '⇔',
  '\\hArr': '⇔',
  '\\harr': '↔',
  '\\hookleftarrow': '↩',
  '\\hookrightarrow': '↪',
  '\\iff': '⇔',
  '\\impliedby': '⇐',
  '\\implies': '⇒',
  '\\Larr': '⇐',
  '\\lArr': '⇐',
  '\\larr': '←',
  '\\leadsto': '⇝',
  '\\leftarrowtail': '↢',
  '\\leftharpoondown': '↽',
  '\\leftharpoonup': '↼',
  '\\leftleftarrows': '⇇',
  '\\leftrightarrows': '⇆',
  '\\leftrightharpoons': '⇋',
  '\\leftrightsquigarrow': '↭',
  '\\Lleftarrow': '⇚',
  '\\longleftarrow': '⟵',
  '\\Longleftarrow': '⟸',
  '\\longleftrightarrow': '⟷',
  '\\Longleftrightarrow': '⟺',
  '\\longmapsto': '⟼',
  '\\longrightarrow': '⟶',
  '\\Longrightarrow': '⟹',
  '\\looparrowleft': '↫',
  '\\looparrowright': '↬',
  '\\Lrarr': '⇔',
  '\\lrArr': '⇔',
  '\\lrarr': '↔',
  '\\Lsh': '↰',
  '\\nearrow': '↗',
  '\\nleftarrow': '↚',
  '\\nLeftarrow': '⇍',
  '\\nleftrightarrow': '↮',
  '\\nLeftrightarrow': '⇎',
  '\\nrightarrow': '↛',
  '\\nRightarrow': '⇏',
  '\\nwarrow': '↖',
  '\\rArr': '⇒',
  '\\rarr': '→',
  '\\restriction': '↾',
  '\\rightarrowtail': '↣',
  '\\rightharpoondown': '⇁',
  '\\rightharpoonup': '⇀',
  '\\rightleftarrows': '⇄',
  '\\rightleftharpoons': '⇌',
  '\\rightrightarrows': '⇉',
  '\\rightsquigarrow': '⇝',
  '\\Rrightarrow': '⇛',
  '\\Rsh': '↱',
  '\\searrow': '↘',
  '\\swarrow': '↙',
  '\\to': '→',
  '\\twoheadleftarrow': '↞',
  '\\twoheadrightarrow': '↠',
  '\\Uarr': '⇑',
  '\\uArr': '⇑',
  '\\uarr': '↑',
  '\\upharpoonleft': '↿',
  '\\upharpoonright': '↾',
  '\\upuparrows': '⇈',
  '\\complement': '∁',
  '\\therefore': '∴',
  '\\because': '∵',
  '\\empty': '∅',
  '\\varnothing': '∅',
  '\\exist': '∃',
  '\\nexists': '∄',
  '\\mid': '|',
  '\\isin': '∈',
  '\\ni': '∋',
  '\\lnot': '¬',
  '\\\\': '↵',
  '\\newline': '↵',
  '\\allowbreak': 'break',
  '\\nobreak': 'no break',
  '\\,': 'thin',
  '\\thinspace': 'thin',
  '\\>': 'med',
  '\\:': 'med',
  '\\medspace': 'med',
  '\\;': 'thick',
  '\\thickspace': 'thick',
  '\\enspace': 'en',
  '\\quad': 'quad',
  '\\qquad': 'qquad',
  '\\!': 'tight',
  '\\negthinspace': 'tight',
  '\\negmedspace': 'tighter',
  '\\negthickspace': 'tightest',
  '\\nobreakspace': 'nbsp',
  '\\space': 'space',
  '\\mathstrut': 'strut',
  '\\bf': '𝐁',
  '\\sf': 'Sans',
  '\\rm': 'Roman',
  '\\it': '𝐼',
  '\\tt': 'Mono',
  '\\cal': '𝒜',
  '\\Huge': 'Huge',
  '\\huge': 'huge',
  '\\LARGE': 'LARGE',
  '\\Large': 'Large',
  '\\large': 'large',
  '\\normalsize': 'normal',
  '\\small': 'small',
  '\\footnotesize': 'footnote',
  '\\scriptsize': 'script',
  '\\tiny': 'tiny',
  '\\displaystyle': '∑',
  '\\textstyle': '∑',
  '\\scriptstyle': 'x₂',
  '\\scriptscriptstyle': 'x₍₂₎',
  '\\limits': 'limⁿ₀',
  '\\nolimits': 'lim₀ⁿ',
  '\\dots': '…',
  '\\cdots': '⋯',
  '\\ddots': '⋱',
  '\\ldots': '…',
  '\\vdots': '⋮',
  '\\dotsb': '⋯',
  '\\dotsc': '…',
  '\\dotsi': '⋯',
  '\\dotsm': '⋯',
  '\\dotso': '…',
  '\\mathellipsis': '…',
  '\\KaTeX': 'KaTeX',
  '\\LaTeX': 'LaTeX',
  '\\TeX': 'TeX',
  '\\%': '%',
  '\\#': '#',
  '\\&': '&',
  '\\_': '_',
  '\\$': '$',
  '\\infin': '∞',
  '\\checkmark': '✓',
  '\\dag': '†',
  '\\dagger': '†',
  '\\ddag': '‡',
  '\\ddagger': '‡',
  '\\Dagger': '‡',
  '\\Box': '□',
  '\\square': '□',
  '\\angle': '∠',
  '\\measuredangle': '∡',
  '\\sphericalangle': '∢',
  '\\top': '⊤',
  '\\bot': '⊥',
  '\\colon': ':',
  '\\backprime': '‵',
  '\\prime': '′',
  '\\lq': '‘',
  '\\rq': '’',
  '\\bigtriangledown': '▽',
  '\\bigtriangleup': '△',
  '\\blacktriangle': '▲',
  '\\blacktriangledown': '▼',
  '\\blacktriangleleft': '◀',
  '\\blacktriangleright': '▶',
  '\\triangle': '△',
  '\\triangledown': '▽',
  '\\triangleleft': '◁',
  '\\triangleright': '▷',
  '\\diamond': '⋄',
  '\\Diamond': '◇',
  '\\lozenge': '◊',
  '\\blacklozenge': '◆',
  '\\star': '⋆',
  '\\bigstar': '★',
  '\\clubsuit': '♣',
  '\\clubs': '♣',
  '\\diamondsuit': '♢',
  '\\diamonds': '♢',
  '\\heartsuit': '♡',
  '\\hearts': '♡',
  '\\spadesuit': '♠',
  '\\spades': '♠',
  '\\maltese': '✠',
  '\\flat': '♭',
  '\\natural': '♮',
  '\\sharp': '♯',
  '\\surd': '√',
  '\\degree': '°',
  '\\mho': '℧',
  '\\diagdown': '╲',
  '\\diagup': '╱',
  '\\P': '¶',
  '\\S': '§',
  '\\sect': '§',
  '\\copyright': '©',
  '\\circledR': '®',
  '\\circledS': 'Ⓢ',
  '\\pounds': '£',
  '\\mathsterling': '£',
  '\\yen': '¥',
  '\\minuso': '⦵',
}

export const KATEX_TEMPLATE_PREVIEWS: Record<string, string> = {
  '\\begin{array}{#?}#?\\end{array}': '[grid]',
  '\\begin{cases}#?\\end{cases}': '{ cases',
  '\\begin{rcases}#?\\end{rcases}': 'cases }',
  '\\begin{smallmatrix}#?\\end{smallmatrix}': 'small ▦',
  '\\begin{subarray}{#?}#?\\end{subarray}': 'x₍ᵢⱼ₎',
  '\\begin{equation}#?\\end{equation}': 'equation',
  '\\begin{equation*}#?\\end{equation*}': 'equation*',
  '\\begin{split}#?\\end{split}': 'split =',
  '\\begin{align}#?\\end{align}': 'align =',
  '\\begin{align*}#?\\end{align*}': 'align*',
  '\\begin{aligned}#?\\end{aligned}': 'aligned',
  '\\begin{alignat}{#?}#?\\end{alignat}': 'align at',
  '\\begin{alignat*}{#?}#?\\end{alignat*}': 'align at*',
  '\\begin{alignedat}{#?}#?\\end{alignedat}': 'aligned at',
  '\\begin{gather}#?\\end{gather}': 'gather',
  '\\begin{gather*}#?\\end{gather*}': 'gather*',
  '\\begin{gathered}#?\\end{gathered}': 'gathered',
  '\\begin{CD}#?\\end{CD}': 'A → B',
  '\\begin{darray}{#?}#?\\end{darray}': 'D grid',
  '\\begin{dcases}#?\\end{dcases}': 'D {cases',
  '\\begin{drcases}#?\\end{drcases}': 'D cases}',
  '\\begin{matrix*}[#?]#?\\end{matrix*}': '□*',
  '\\begin{pmatrix*}[#?]#?\\end{pmatrix*}': '(□)*',
  '\\begin{bmatrix*}[#?]#?\\end{bmatrix*}': '[□]*',
  '\\begin{Bmatrix*}[#?]#?\\end{Bmatrix*}': '{□}*',
  '\\begin{vmatrix*}[#?]#?\\end{vmatrix*}': '|□|*',
  '\\begin{Vmatrix*}[#?]#?\\end{Vmatrix*}': '‖□‖*',
  '\\tilde{#?}': 'ã',
  '\\widetilde{#?}': 'ãã',
  '\\utilde{#?}': 'a̰',
  '\\acute{#?}': 'á',
  '\\bar{#?}': 'ā',
  '\\breve{#?}': 'ă',
  '\\check{#?}': 'ǎ',
  '\\dot{#?}': 'ȧ',
  '\\ddot{#?}': 'ä',
  '\\dddot{#?}': 'a⃛',
  '\\ddddot{#?}': 'a⃜',
  '\\grave{#?}': 'à',
  '\\hat{#?}': 'â',
  '\\widehat{#?}': 'ââ',
  '\\widecheck{#?}': 'ǎǎ',
  '\\mathring{#?}': 'å',
  '\\vec{#?}': 'a⃗',
  '\\overline{#?}': 'a̅',
  '\\underline{#?}': 'a̲',
  '\\underbar{#?}': 'a̱',
  '\\overbrace{#?}^{#?}': '⏞',
  '\\underbrace{#?}_{#?}': '⏟',
  '\\overbracket{#?}^{#?}': '⎴',
  '\\underbracket{#?}_{#?}': '⎵',
  '\\overgroup{#?}': 'a︷',
  '\\undergroup{#?}': 'a︸',
  '\\overleftarrow{#?}': 'a⃖',
  '\\overrightarrow{#?}': 'a⃗',
  '\\Overrightarrow{#?}': 'a⃗⃗',
  '\\underleftarrow{#?}': '← under',
  '\\underrightarrow{#?}': '→ under',
  '\\overleftrightarrow{#?}': 'a⃡',
  '\\underleftrightarrow{#?}': '↔ under',
  '\\overleftharpoon{#?}': 'a↼',
  '\\overrightharpoon{#?}': 'a⇀',
  '\\overlinesegment{#?}': 'AB̅',
  '\\underlinesegment{#?}': 'AB̲',
  "\\'{#?}": 'á',
  '\\`{#?}': 'à',
  '\\^{#?}': 'â',
  '\\~{#?}': 'ã',
  '\\={#?}': 'ā',
  '\\u{#?}': 'ă',
  '\\.{#?}': 'ȧ',
  '\\"{#?}': 'ä',
  '\\r{#?}': 'å',
  '\\H{#?}': 'a̋',
  '\\v{#?}': 'ǎ',
  '\\tfrac{#?}{#?}': 'a/b',
  '\\dfrac{#?}{#?}': 'a⁄b',
  '\\cfrac{#?}{#?}': 'a⁄b⁄c',
  '\\binom{#?}{#?}': '(n k)',
  '\\dbinom{#?}{#?}': '(n k)',
  '\\tbinom{#?}{#?}': '(n k)',
  '\\genfrac{#?}{#?}{#?}{#?}{#?}{#?}': '(a/b)',
  '{#? \\over #?}': 'a over b',
  '{#? \\above{#?} #?}': 'a above b',
  '{#? \\choose #?}': 'n choose k',
  '{#? \\brace #?}': '{a/b}',
  '{#? \\brack #?}': '[a/b]',
  '\\xleftarrow{#?}': '← label',
  '\\xrightarrow[#?]{#?}': 'label →',
  '\\xLeftarrow{#?}': '⇐ label',
  '\\xRightarrow{#?}': 'label ⇒',
  '\\xleftrightarrow{#?}': '↔ label',
  '\\xLeftrightarrow{#?}': '⇔ label',
  '\\xhookleftarrow{#?}': '↩ label',
  '\\xhookrightarrow{#?}': 'label ↪',
  '\\xtwoheadleftarrow{#?}': '↞ label',
  '\\xtwoheadrightarrow{#?}': 'label ↠',
  '\\xleftharpoonup{#?}': '↼ label',
  '\\xrightharpoonup{#?}': 'label ⇀',
  '\\xleftharpoondown{#?}': '↽ label',
  '\\xrightharpoondown{#?}': 'label ⇁',
  '\\xleftrightharpoons{#?}': '⇋ label',
  '\\xrightleftharpoons{#?}': 'label ⇌',
  '\\xtofrom{#?}': '⇄ label',
  '\\xmapsto{#?}': 'label ↦',
  '\\xlongequal{#?}': 'label =',
  '\\bra{#?}': '⟨ψ|',
  '\\ket{#?}': '|ψ⟩',
  '\\braket{#?}': '⟨φ|ψ⟩',
  '\\Bra{#?}': '⟨Ψ|',
  '\\Ket{#?}': '|Ψ⟩',
  '\\Braket{#?}': '⟨Φ|Ψ⟩',
  '\\Set{#?}': '{x | P}',
  '\\set{#?}': '{x | P}',
  '\\cancel{#?}': 'x̸',
  '\\bcancel{#?}': 'x╲',
  '\\xcancel{#?}': 'x⃠',
  '\\sout{#?}': 'x̶',
  '\\boxed{#?}': '□x',
  '\\phase{#?}': '∠x',
  '\\tag{#?}': '(#)',
  '\\tag*{#?}': '#',
  '\\stackrel{#?}{#?}': 'a over b',
  '\\raisebox{#?}{#?}': 'raise x',
  '\\vcenter{#?}': 'center y',
  '\\hbox{#?}': 'text box',
  '\\substack{#?}': 'a/b',
  '\\mathllap{#?}': '←x',
  '\\mathrlap{#?}': 'x→',
  '\\mathclap{#?}': '↔x',
  '\\smash{#?}': 'smash',
  '\\smash[b]{#?}': 'smash↓',
  '\\llap{#?}': '←text',
  '\\rlap{#?}': 'text→',
  '\\clap{#?}': '↔text',
  '\\phantom{#?}': 'ghost',
  '\\hphantom{#?}': 'blank width',
  '\\vphantom{#?}': 'blank height',
  '\\kern{#?}': 'space',
  '\\mkern{#?}': 'math space',
  '\\mskip{#?}': 'math skip',
  '\\hskip{#?}': 'h skip',
  '\\hspace{#?}': 'h space',
  '\\hspace*{#?}': 'fixed space',
  '\\mathrm{#?}': 'Roman',
  '\\mathbf{#?}': '𝐁',
  '\\mathsf{#?}': 'Sans',
  '\\mathnormal{#?}': '𝑥',
  '\\textbf{#?}': 'Bold',
  '\\textsf{#?}': 'Sans',
  '\\textrm{#?}': 'Roman',
  '\\bold{#?}': '𝐁',
  '\\mathsfit{#?}': '𝘈',
  '\\textnormal{#?}': 'Normal',
  '\\boldsymbol{#?}': '𝛂',
  '\\Bbb{#?}': '𝔸',
  '\\text{#?}': 'text',
  '\\bm{#?}': '𝛂',
  '\\mathbb{#?}': '𝔸',
  '\\textup{#?}': 'Up',
  '\\textmd{#?}': 'Medium',
  '\\frak{#?}': '𝔄',
  '\\mathit{#?}': '𝐼',
  '\\mathtt{#?}': 'Mono',
  '\\mathfrak{#?}': '𝔄',
  '\\textit{#?}': 'Italic',
  '\\texttt{#?}': 'Mono',
  '\\mathcal{#?}': '𝒜',
  '\\emph{#?}': 'Emph',
  '\\mathscr{#?}': '𝒜',
  '\\pmb{#?}': 'bold x',
  '\\mathbin{#?}': 'a + b',
  '\\mathclose{#?}': ')',
  '\\mathinner{#?}': '(x)',
  '\\mathop{#?}': 'op',
  '\\mathopen{#?}': '(',
  '\\mathord{#?}': 'x',
  '\\mathpunct{#?}': ',',
  '\\mathrel{#?}': '=',
  '\\textcolor{#?}{#?}': 'color x',
  '\\colorbox{#?}{#?}': 'bg color',
  '\\fcolorbox{#?}{#?}{#?}': 'border box',
  '\\color{#?}': 'color',
  '\\verb|#?|': '|code|',
  '\\href{#?}{#?}': 'link',
  '\\url{#?}': 'URL',
  '\\includegraphics[height=#?]{#?}': 'image',
  '\\htmlId{#?}{#?}': '#id',
  '\\htmlClass{#?}{#?}': '.class',
  '\\htmlStyle{#?}{#?}': 'style',
  '\\htmlData{#?}{#?}': 'data',
  '\\def\\foo{#?}': 'define f',
  '\\gdef\\foo#1{#?}': 'global f',
  '\\edef\\foo{#?}': 'expand f',
  '\\xdef\\foo{#?}': 'xdefine f',
  '\\let\\foo=\\bar': 'let f=g',
  '\\futurelet\\foo\\bar #?': 'future let',
  '\\global\\def\\foo{#?}': 'global def',
  '\\newcommand\\foo[1]{#?}': 'new f(x)',
  '\\renewcommand\\foo[1]{#?}': 'renew f(x)',
  '\\providecommand\\foo[1]{#?}': 'provide f(x)',
  '\\char"#?': 'char',
  '\\mathchoice{#?}{#?}{#?}{#?}': 'style choice',
  '\\TextOrMath{#?}{#?}': 'text/math',
  '\\@ifstar{#?}{#?}': '* ?',
  '\\@ifnextchar#?{#?}{#?}': 'next ?',
  '\\@firstoftwo{#?}{#?}': 'first',
  '\\@secondoftwo{#?}{#?}': 'second',
  '\\relax': 'relax',
  '\\expandafter#?': 'expand after',
  '\\noexpand#?': 'no expand',
}

